// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.9.2
// source: nozomi.proto

package nozomi

import (
	ext "github.com/Luoxin/sexy/us/ext"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotifyReq_Detail_ErrCode int32

const (
	// @desc: 默认值
	NotifyReq_Detail_Success NotifyReq_Detail_ErrCode = 0 // 成功
)

// Enum value maps for NotifyReq_Detail_ErrCode.
var (
	NotifyReq_Detail_ErrCode_name = map[int32]string{
		0: "Success",
	}
	NotifyReq_Detail_ErrCode_value = map[string]int32{
		"Success": 0,
	}
)

func (x NotifyReq_Detail_ErrCode) Enum() *NotifyReq_Detail_ErrCode {
	p := new(NotifyReq_Detail_ErrCode)
	*p = x
	return p
}

func (x NotifyReq_Detail_ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotifyReq_Detail_ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_nozomi_proto_enumTypes[0].Descriptor()
}

func (NotifyReq_Detail_ErrCode) Type() protoreflect.EnumType {
	return &file_nozomi_proto_enumTypes[0]
}

func (x NotifyReq_Detail_ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotifyReq_Detail_ErrCode.Descriptor instead.
func (NotifyReq_Detail_ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_nozomi_proto_rawDescGZIP(), []int{0, 0, 0}
}

// aaa
// @desc: xxx
// @gorm: xxx
// lalala
type NotifyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A uint32            `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B *NotifyReq_Detail `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *NotifyReq) Reset() {
	*x = NotifyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nozomi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyReq) ProtoMessage() {}

func (x *NotifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_nozomi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyReq.ProtoReflect.Descriptor instead.
func (*NotifyReq) Descriptor() ([]byte, []int) {
	return file_nozomi_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyReq) GetA() uint32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *NotifyReq) GetB() *NotifyReq_Detail {
	if x != nil {
		return x.B
	}
	return nil
}

type NotifyRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NotifyRsp) Reset() {
	*x = NotifyRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nozomi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRsp) ProtoMessage() {}

func (x *NotifyRsp) ProtoReflect() protoreflect.Message {
	mi := &file_nozomi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRsp.ProtoReflect.Descriptor instead.
func (*NotifyRsp) Descriptor() ([]byte, []int) {
	return file_nozomi_proto_rawDescGZIP(), []int{1}
}

type NotifyReq_Detail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @desc: xxx
	Da string `protobuf:"bytes,1,opt,name=da,proto3" json:"da,omitempty"`
}

func (x *NotifyReq_Detail) Reset() {
	*x = NotifyReq_Detail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nozomi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyReq_Detail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyReq_Detail) ProtoMessage() {}

func (x *NotifyReq_Detail) ProtoReflect() protoreflect.Message {
	mi := &file_nozomi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyReq_Detail.ProtoReflect.Descriptor instead.
func (*NotifyReq_Detail) Descriptor() ([]byte, []int) {
	return file_nozomi_proto_rawDescGZIP(), []int{0, 0}
}

func (x *NotifyReq_Detail) GetDa() string {
	if x != nil {
		return x.Da
	}
	return ""
}

var File_nozomi_proto protoreflect.FileDescriptor

var file_nozomi_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6e, 0x6f, 0x7a, 0x6f, 0x6d, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x6e, 0x6f, 0x7a, 0x6f, 0x6d, 0x69, 0x1a, 0x09, 0x65, 0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x73, 0x0a, 0x09, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x12, 0x0c,
	0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x61, 0x12, 0x26, 0x0a, 0x01,
	0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6e, 0x6f, 0x7a, 0x6f, 0x6d, 0x69,
	0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x52, 0x01, 0x62, 0x1a, 0x30, 0x0a, 0x06, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x0e,
	0x0a, 0x02, 0x64, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x64, 0x61, 0x22, 0x16,
	0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x10, 0x00, 0x22, 0x0b, 0x0a, 0x09, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x52, 0x73, 0x70, 0x32, 0x2e, 0x0a, 0x06, 0x6e, 0x6f, 0x7a, 0x6f, 0x6d, 0x69, 0x12, 0x24, 0x0a,
	0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x0b, 0x2e, 0x65, 0x78, 0x74, 0x2e, 0x45, 0x78,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x65, 0x78, 0x74, 0x2e, 0x45, 0x78, 0x74, 0x52, 0x65,
	0x71, 0x22, 0x00, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x4c, 0x75, 0x6f, 0x78, 0x69, 0x6e, 0x2f, 0x73, 0x65, 0x78, 0x79, 0x2f, 0x75, 0x73,
	0x2f, 0x6e, 0x6f, 0x7a, 0x6f, 0x6d, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nozomi_proto_rawDescOnce sync.Once
	file_nozomi_proto_rawDescData = file_nozomi_proto_rawDesc
)

func file_nozomi_proto_rawDescGZIP() []byte {
	file_nozomi_proto_rawDescOnce.Do(func() {
		file_nozomi_proto_rawDescData = protoimpl.X.CompressGZIP(file_nozomi_proto_rawDescData)
	})
	return file_nozomi_proto_rawDescData
}

var file_nozomi_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nozomi_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nozomi_proto_goTypes = []interface{}{
	(NotifyReq_Detail_ErrCode)(0), // 0: nozomi.NotifyReq.Detail.ErrCode
	(*NotifyReq)(nil),             // 1: nozomi.NotifyReq
	(*NotifyRsp)(nil),             // 2: nozomi.NotifyRsp
	(*NotifyReq_Detail)(nil),      // 3: nozomi.NotifyReq.Detail
	(*ext.ExtReq)(nil),            // 4: ext.ExtReq
}
var file_nozomi_proto_depIdxs = []int32{
	3, // 0: nozomi.NotifyReq.b:type_name -> nozomi.NotifyReq.Detail
	4, // 1: nozomi.nozomi.Notify:input_type -> ext.ExtReq
	4, // 2: nozomi.nozomi.Notify:output_type -> ext.ExtReq
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_nozomi_proto_init() }
func file_nozomi_proto_init() {
	if File_nozomi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nozomi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nozomi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nozomi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyReq_Detail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nozomi_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nozomi_proto_goTypes,
		DependencyIndexes: file_nozomi_proto_depIdxs,
		EnumInfos:         file_nozomi_proto_enumTypes,
		MessageInfos:      file_nozomi_proto_msgTypes,
	}.Build()
	File_nozomi_proto = out.File
	file_nozomi_proto_rawDesc = nil
	file_nozomi_proto_goTypes = nil
	file_nozomi_proto_depIdxs = nil
}
