// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.9.2
// source: ext.proto

package ext

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExtReq) Reset() {
	*x = ExtReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ext_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtReq) ProtoMessage() {}

func (x *ExtReq) ProtoReflect() protoreflect.Message {
	mi := &file_ext_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtReq.ProtoReflect.Descriptor instead.
func (*ExtReq) Descriptor() ([]byte, []int) {
	return file_ext_proto_rawDescGZIP(), []int{0}
}

type ExtRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Buf []byte `protobuf:"bytes,1,opt,name=buf,proto3" json:"buf,omitempty"`
}

func (x *ExtRsp) Reset() {
	*x = ExtRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ext_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtRsp) ProtoMessage() {}

func (x *ExtRsp) ProtoReflect() protoreflect.Message {
	mi := &file_ext_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtRsp.ProtoReflect.Descriptor instead.
func (*ExtRsp) Descriptor() ([]byte, []int) {
	return file_ext_proto_rawDescGZIP(), []int{1}
}

func (x *ExtRsp) GetBuf() []byte {
	if x != nil {
		return x.Buf
	}
	return nil
}

var File_ext_proto protoreflect.FileDescriptor

var file_ext_proto_rawDesc = []byte{
	0x0a, 0x09, 0x65, 0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x65, 0x78, 0x74,
	0x22, 0x08, 0x0a, 0x06, 0x45, 0x78, 0x74, 0x52, 0x65, 0x71, 0x22, 0x1a, 0x0a, 0x06, 0x45, 0x78,
	0x74, 0x52, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x75, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x03, 0x62, 0x75, 0x66, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4c, 0x75, 0x6f, 0x78, 0x69, 0x6e, 0x2f, 0x73, 0x65, 0x78, 0x79,
	0x2f, 0x75, 0x73, 0x2f, 0x65, 0x78, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ext_proto_rawDescOnce sync.Once
	file_ext_proto_rawDescData = file_ext_proto_rawDesc
)

func file_ext_proto_rawDescGZIP() []byte {
	file_ext_proto_rawDescOnce.Do(func() {
		file_ext_proto_rawDescData = protoimpl.X.CompressGZIP(file_ext_proto_rawDescData)
	})
	return file_ext_proto_rawDescData
}

var file_ext_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ext_proto_goTypes = []interface{}{
	(*ExtReq)(nil), // 0: ext.ExtReq
	(*ExtRsp)(nil), // 1: ext.ExtRsp
}
var file_ext_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ext_proto_init() }
func file_ext_proto_init() {
	if File_ext_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ext_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ext_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ext_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ext_proto_goTypes,
		DependencyIndexes: file_ext_proto_depIdxs,
		MessageInfos:      file_ext_proto_msgTypes,
	}.Build()
	File_ext_proto = out.File
	file_ext_proto_rawDesc = nil
	file_ext_proto_goTypes = nil
	file_ext_proto_depIdxs = nil
}
